---
name: Branches

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: branches-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  coverage:
    name: Coverage
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@69d61153fe24338ea983dd657496f0bc8b4cd819 # workflow-tests-v5
    with:
      source_branch: ${{ github.ref_name }}
      unit_tests: false
      integration_tests: false
      unit_coverage: true
      unconditional: true
      unit_coverage_command: "nix develop .#coverage -c cargo llvm-cov --workspace --lib --lcov --output-path coverage.lcov"
      runner: depot-ubuntu-24.04-4
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
