---
name: Zizmor
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: [".github/**"]
  merge_group:
    types: [checks_requested]
concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-zizmor
  cancel-in-progress: true
permissions:
  contents: read
  security-events: write
jobs:
  zizmor:
    uses: hoprnet/hopr-workflows/.github/workflows/checks-zizmor.yaml@7d8e6dfe4cfacb23a42857171d7426467686970e # workflow-checks-zizmor-v1
    permissions:
      contents: read
      security-events: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      runner: depot-ubuntu-24.04-4
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
