---
name: PR

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  id-token: write # zizmor: ignore[excessive-permissions]

concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-pr
  cancel-in-progress: true

jobs:
  validate-pr-title:
    name: Validate title
    if: github.event_name == 'pull_request'
    runs-on: depot-ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            build
            chore
            docs
            style
            refactor
            perf
            test
          requireScope: false
          ignoreLabels: |
            bot
            ignore-semantic-pull-request

  label:
    name: Add labels
    if: github.event_name == 'pull_request'
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/labeler@77a4082b841706ac431479b7e2bb11216ffef250 # main on 20.02.2025
        with:
          sync-labels: true
      - name: Add "external" label for forked PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_REPO: ${{ github.repository }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [[ "$HEAD_REPO" != "$BASE_REPO" ]]; then
            gh pr edit "$PR_NUMBER" --add-label "external"
          fi

  checks:
    name: Check
    uses: hoprnet/hopr-workflows/.github/workflows/checks.yaml@bbd22e57cf954c15f0a6051d59329857809141dd # workflow-checks-v1
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      runner_small: depot-ubuntu-24.04
      runner_large: depot-ubuntu-24.04-4
      deps_command: 'nix develop .#ci -c bash -c "cargo machete"'
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  tests:
    name: Test
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@798d791de5c5485c3043049781dfd0938539a36a # workflow-tests-v6
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      enable_unit_tests: true
      unit_test_command: "nix develop -c cargo test --lib"
      enable_nightly_tests: true
      nightly_test_command: "nix develop .#nightly -c cargo test -Z panic-abort-tests --lib"
      enable_unit_coverage: true
      unit_coverage_command: "nix develop .#coverage -c cargo llvm-cov --workspace --lib --lcov --output-path coverage.lcov"
      runner_unit: depot-ubuntu-24.04-4
      test_timeout: 60
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-candidate-binaries:
    name: Build Candidate Binaries
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 20
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        binary:
          - hopli
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          persist-credentials: false
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@c8d45034bb33307dfda3b4dfcd1fc4000cadc05a # setup-nix-v1
        with:
          cachix_cache_name: hopli
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build binary
        shell: bash
        env:
          BINARY: ${{ matrix.binary }}
        run: nix build .#"${BINARY}"-candidate

  build-binaries:
    name: Binary ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: depot-ubuntu-24.04-4
            build_command: nix build -L .#binary-hopli-x86_64-linux
            required_label: ""
          - architecture: aarch64-linux
            runner: depot-ubuntu-24.04-arm-4
            build_command: nix build -L .#binary-hopli-aarch64-linux
            required_label: "binary:aarch64-linux"
          - architecture: aarch64-darwin
            runner: depot-macos-15
            build_command: nix build -L .#binary-hopli-aarch64-darwin
            required_label: binary:aarch64-darwin
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@fa71078959cf9f892185e8df16551720693a2cd1 # 0.9.3
    permissions:
      contents: read
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      architecture: ${{ matrix.architecture }}
      build_command: ${{ matrix.build_command }}
      binary: hopli
      runner: ${{ matrix.runner }}
      timeout_minutes: 120
      enabled: ${{ matrix.required_label == '' || contains(github.event.pull_request.labels.*.name, matrix.required_label) }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}

  build-docker:
    name: Docker
    needs: build-binaries
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@fa71078959cf9f892185e8df16551720693a2cd1 # 0.9.3
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      build_matrix: >-
        [
          {
            "runner": "depot-ubuntu-24.04-4",
            "architecture": "x86_64-linux",
            "build_command": "nix build -L .#docker-hopli-x86_64-linux"
          }
        ]
      docker_image_name: hopli
      docker_image_format: skopeo
      fail_on_scan_vulnerabilities: ${{ vars.FAIL_ON_SCAN_VULNERABILITIES }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
